appName: ordersapp
namespace: default
replicaCount: 2
image:
  name: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/lior-portfolio
  tag: 3.0.53
ingress:
  enabled: true
  host: nominomi.hopto.org
  className: nginx
  tls:
    secret:
      name: example-tls
secret:
  name: external-secrets
clusterissuer:
  name: letsencrypt-prod
  email: masrab11@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  ingress:
    class: nginx
mysql:
  architecture: replication
  auth:
    database: "orders_management"
    existingSecret: "mysql-secrets"
  metrics:
    enabled: true
