appName: ordersapp
namespace: default
replicaCount: 2
image:
  name: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/lior-portfolio
  tag: 3.0.11
ingress:
  enabled: true
  host: democrm-lior.ddns.net
  className: nginx
  tls:
    secret:
      name: example-tls
# secret:
#   name: default-secrets
#   data:
#     DATABASE_USER: root
#     DATABASE_PASS: "12345678"
#     DATABASE_HOST: ordersapp-mysql-primary-headless
#     DATABASE_NAME: orders_management

secret:
  name: external-secrets
  
clusterissuer:
  name: letsencrypt-prod
  email: masrab11@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  ingress:
    class: nginx
mysql:
  architecture: replication
  auth:
    rootPassword: "12345678"
    database: "orders_management"
