apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsofapp
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./infra-apps
    repoURL: 'git@github.com:deempa/GitOps-Config-Portfolio.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default