apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-release-cert-manager
  namespace: default
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.12.0
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
