{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterissuer.name }}
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~* /(css|html|png) {
          rewrite ^/(.*)$ https://lior-porftolio-staticfiles.s3.eu-west-2.amazonaws.com/$1 break;
          proxy_pass https://lior-porftolio-staticfiles.s3.eu-west-2.amazonaws.com$request_uri;
          proxy_set_header Host lior-porftolio-staticfiles.s3.eu-west-2.amazonaws.com;
      }

  labels:
    name: {{ .Values.appName }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.appName }}
            port: 
              number: 80
      # - pathType: Prefix
      #   path: / # <-- your routing logic
      #   backend:
      #     service:
      #       name: static-assets
      #       port:
      #         number: 80 
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secret.name }}
{{- end }}