apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  DATABASE_USER: {{ .Values.secret.data.DATABASE_USER | b64enc| quote }}
  DATABASE_PASS: {{ .Values.secret.data.DATABASE_PASS | b64enc | quote }}
  DATABASE_HOST: {{ .Values.secret.data.DATABASE_HOST | b64enc | quote }}
  DATABASE_NAME: {{ .Values.secret.data.DATABASE_NAME | b64enc | quote }}

  