apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  {{ if .Values.ingress.enabled }}
  type: ClusterIP
  {{ else }}
  type: LoadBalancer
  {{ end }}
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: web
    port: 80
    targetPort: 5000

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: web
      path: /metrics
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  endpoints:
  - port: web