apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  {{ if .Values.ingress.enabled }}
  type: ClusterIP
  {{ else }}
  type: LoadBalancer
  {{ end }}
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: 80
    targetPort: 3000