apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    chart: fluentd
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.4.3
    helm:
      values: |
        livenessProbe:
        readinessProbe:
        fileConfigs:
          01_sources.conf: |-
            <source>
              @type tail
              read_from_head true
              tag kubernetes.*
              path /var/log/containers/*.log
              pos_file /var/log/containers.log.pos
              exclude_path ["/var/log/containers/fluent*"]
              <parse>
                @type multi_format
                    <pattern>
                      format regexp
                      expression /^(?<time>[^ ]*)(?<stream>[^ ]*)[^ ]*(?<log>.*)$/
                      time_format %Y-%m-%dT%H:%M:%S.%NZ
                    </pattern>
                <pattern>
                  format json
                  key log
                </pattern>
              </parse>
            </source>
          02_filters.conf: |-
          03_dispatch.conf: |-
          04_outputs.conf: |-
            <match **>
              @type elasticsearch
              @log_level info
              host elasticsearch-master-hl
              port 9200
              logstash_format true
              scheme http
              path ""
              index_name kube-fluentd
            </match>
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true