apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    chart: kibana
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.4.2
    helm:
      values: |
        elasticsearch:
          hosts: 
            - "elasticsearch.default.svc.cluster.local"
          port: 9200
        savedObjects:
          configmap: "kibanadashboard"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true