apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: default
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.6.1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true